name: tasks_api
description: The interface and models for an API providing access to tasks.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0

dependencies:
  equatable: ^2.0.5
  internet_tasks:
    path: ../internet_tasks
  json_annotation: ^4.8.1
  meta: ^1.7.0
